### PR TITLE
Fixed wrong action condition, which prevented file backup operations.

### PR DESCRIPTION
**Pull request by klebed**
Fixed an issue with file backup operations.
image

### CODE REVIEW

**Comment by YanChii** [comment]
Thank you!

**Comment by YanChii** [comment]
FYI if you want to update to this fix immediately, put this commit number (ccb2b023e7d9d1c868f5195aee7ad3b0b646ff4d) instead of the version number when updating (yes, `ccb2b023e7d9d1c868f5195aee7ad3b0b646ff4d` instead of `v4.1`).

In this case, it is enough to update the node software, no need for mgmt upgrade.

Jan

**Comment by klebed** [comment]
> FYI if you want to update to this fix immediately, put this commit number ([ccb2b02](https://github.com/erigones/esdc-ce/commit/ccb2b023e7d9d1c868f5195aee7ad3b0b646ff4d)) instead of the version number when updating (yes, `ccb2b023e7d9d1c868f5195aee7ad3b0b646ff4d` instead of `v4.1`).
> 
> In this case, it is enough to update the node software, no need for mgmt upgrade.
> 
> Jan

Cool, thanks!
But we use USB-boot, should it be built into image and applied to flash-drives?

**Comment by YanChii** [comment]
Danube Cloud code is independent from platform code and you can upgrade it without touching the platform.
- DC code can be ugraded from GUI/API (or by `esdc-git-upgrade`).
- Platform is upgraded only from cmd line by `esdc-platform-upgrade`.

**Comment by klebed** [comment]
> Danube Cloud code is independent from platform code and you can upgrade it without touching the platform.
> 
>     * DC code can be ugraded from GUI/API (or by `esdc-git-upgrade`).
> 
>     * Platform is upgraded only from cmd line by `esdc-platform-upgrade`.

Yeah! Missed that thing! Platform and DC on nodes has separate version data.
Thanks!

**Comment by YanChii** [comment]
And you can test also the other fix you have reported about that dc_bound DNS. But for that, you need to commit-upgrade the mgmt.

**Pull request merged**
